name: Analyze - Client

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.svelte"
      - "**/*.ts"

env:
  CARGO_TERM_COLOR: always

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: ./client/yarn.lock

      - name: Install dependencies for client
        working-directory: ./client
        run: yarn install

      - name: Ensure style is consistent
        working-directory: ./client
        run: yarn lint
