name: Analyze - Commits

on: [pull_request]

jobs:
  committed:
    name: Analyze - Commits
    runs-on: self-hosted

    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Commits
        uses: crate-ci/committed@master
