name: Analyze - Code Coverage

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "**/*.svelte"
      - "**/*.ts"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "**/*.svelte"
      - "**/*.ts"

jobs:
  coverage:
    name: Analyze - Code Coverage
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: unittests
