name: Release

on:
  push:
    branches: ["main"]
    tags: ["v*"]
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - "*.md"
      - ".*ignore"
      - "benches/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag,
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4.0.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=min
          file: Dockerfile

      - name: Extract metadata (tags, labels) for Alpine Image
        id: meta-alpine
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            prefix=alpine
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=raw,value=

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: ${{ steps.meta-alpine.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.alpine
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Extract metadata (tags, labels) for Distroless Image
        id: meta-distroless
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            prefix=distroless
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=raw,value=

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-distroless.outputs.tags }}
          labels: ${{ steps.meta-distroless.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.distroless
