name: Analyze - Server

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  analyze-clippy:
    runs-on: self-hosted
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: rui314/setup-mold@v1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run:
          cargo clippy --all-features --message-format=json -- -D
          clippy::pedantic -A clippy::must-use-candidate -A clippy::cast-precision-loss | clippy-sarif | tee
          rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

  test-server:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: rui314/setup-mold@v1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Test Server
        run: cargo nextest run
